general.import = ["/home/sushi/.config/alacritty/tokyo.toml"]
general.live_config_reload = true

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono NF"

[font.bold_italic]
family = "JetBrainsMono NF"

[font.italic]
family = "JetBrainsMono NF"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
program = "/run/current-system/sw/bin/fish"

[window]
decorations = "full"
dynamic_title = true
opacity = 1
title = "Alacritty"

[window.padding]
x = 0
y = 2

[terminal]
