#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

$HOME/.config/polybar/launch.sh &
# feh --bg-fill $HOME/Downloads/walls/attack-on-titan.jpg &
feh --bg-fill $HOME/Downloads/wall2/wallpapers/b-367.jpg &
dunst -conf $HOME/.config/dunst/dunstrc &
picom --experimental-backends &
xfce4-power-manager &
blueman-applet &

# bspc monitor DP-0 -d VI VII VIII X IX
# bspc monitor DP-4 -d I II III IV V
# bspc monitor DP-4 -s DP-0

bspc monitor DP-0 -d I II III IV V
bspc monitor DP-4 -d VI VII VIII X IX

bspc config border_width 2
bspc config window_gap 02

bspc config split_ratio 0.55
bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Pycalendar.py state=floating rectangle=800x600+1750+510
