#!/usr/bin/env sh

pgrep -x sxhkd >/dev/null || sxhkd &

xfce4-power-manager &
lxqt-policykit-agent &

$HOME/.config/polybar/launch.sh &
feh --bg-fill $HOME/Downloads/nixos_wall/nix-wallpaper-dracula.png &

bspc monitor DP-4 -d VI VII VIII X IX
bspc monitor DP-2 -d I II III IV V
# bspc monitor DP-0 -s DP-4

# bspc monitor DP-4 -d I II III IV V VI VII VIII X IX
# bspc monitor DP-0 -d

bspc config border_width 1
bspc config window_gap 0

bspc config split_ratio 0.55
bspc config focused_border_color "#f5a1df"
bspc config normal_border_color "#6e6a86"
bspc config borderless_monocle true
bspc config gapless_monocle true
